version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
